// Code generated by protoc-gen-go.
// source: server/gnode/gnode.proto
// DO NOT EDIT!

/*
Package gnode is a generated protocol buffer package.

It is generated from these files:
	server/gnode/gnode.proto

It has these top-level messages:
	AntMes
	AntRet
	PingRet
	AskConnectionRequest
	SendFileRequest
	SendFileRet
	EmptyRet
	GetFileRequest
	GetFileRet
*/
package gnode

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AntMes struct {
	Id           string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Origin       string   `protobuf:"bytes,2,opt,name=origin" json:"origin,omitempty"`
	FromClient   string   `protobuf:"bytes,3,opt,name=from_client,json=fromClient" json:"from_client,omitempty"`
	Target       string   `protobuf:"bytes,4,opt,name=target" json:"target,omitempty"`
	IsAnswer     bool     `protobuf:"varint,5,opt,name=isAnswer" json:"isAnswer,omitempty"`
	ReturnAnswer bool     `protobuf:"varint,6,opt,name=return_answer,json=returnAnswer" json:"return_answer,omitempty"`
	IsPathWriter bool     `protobuf:"varint,7,opt,name=is_path_writer,json=isPathWriter" json:"is_path_writer,omitempty"`
	OriginId     string   `protobuf:"bytes,8,opt,name=origin_id,json=originId" json:"origin_id,omitempty"`
	Path         []string `protobuf:"bytes,9,rep,name=path" json:"path,omitempty"`
	PathIndex    int32    `protobuf:"varint,10,opt,name=path_index,json=pathIndex" json:"path_index,omitempty"`
	Function     string   `protobuf:"bytes,11,opt,name=function" json:"function,omitempty"`
	Args         []string `protobuf:"bytes,12,rep,name=args" json:"args,omitempty"`
	TransferId   string   `protobuf:"bytes,13,opt,name=transfer_id,json=transferId" json:"transfer_id,omitempty"`
	Order        int64    `protobuf:"varint,14,opt,name=order" json:"order,omitempty"`
	NbBlock      int64    `protobuf:"varint,15,opt,name=nb_block,json=nbBlock" json:"nb_block,omitempty"`
	Replicas     int32    `protobuf:"varint,16,opt,name=replicas" json:"replicas,omitempty"`
	Size         int64    `protobuf:"varint,17,opt,name=size" json:"size,omitempty"`
	TargetedPath string   `protobuf:"bytes,18,opt,name=targeted_path,json=targetedPath" json:"targeted_path,omitempty"`
	NoBlocking   bool     `protobuf:"varint,19,opt,name=no_blocking,json=noBlocking" json:"no_blocking,omitempty"`
	Debug        bool     `protobuf:"varint,20,opt,name=debug" json:"debug,omitempty"`
	Data         []byte   `protobuf:"bytes,21,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *AntMes) Reset()                    { *m = AntMes{} }
func (m *AntMes) String() string            { return proto.CompactTextString(m) }
func (*AntMes) ProtoMessage()               {}
func (*AntMes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AntMes) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AntMes) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *AntMes) GetFromClient() string {
	if m != nil {
		return m.FromClient
	}
	return ""
}

func (m *AntMes) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *AntMes) GetIsAnswer() bool {
	if m != nil {
		return m.IsAnswer
	}
	return false
}

func (m *AntMes) GetReturnAnswer() bool {
	if m != nil {
		return m.ReturnAnswer
	}
	return false
}

func (m *AntMes) GetIsPathWriter() bool {
	if m != nil {
		return m.IsPathWriter
	}
	return false
}

func (m *AntMes) GetOriginId() string {
	if m != nil {
		return m.OriginId
	}
	return ""
}

func (m *AntMes) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *AntMes) GetPathIndex() int32 {
	if m != nil {
		return m.PathIndex
	}
	return 0
}

func (m *AntMes) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *AntMes) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *AntMes) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

func (m *AntMes) GetOrder() int64 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *AntMes) GetNbBlock() int64 {
	if m != nil {
		return m.NbBlock
	}
	return 0
}

func (m *AntMes) GetReplicas() int32 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *AntMes) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *AntMes) GetTargetedPath() string {
	if m != nil {
		return m.TargetedPath
	}
	return ""
}

func (m *AntMes) GetNoBlocking() bool {
	if m != nil {
		return m.NoBlocking
	}
	return false
}

func (m *AntMes) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *AntMes) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AntRet struct {
	Ack bool   `protobuf:"varint,1,opt,name=ack" json:"ack,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *AntRet) Reset()                    { *m = AntRet{} }
func (m *AntRet) String() string            { return proto.CompactTextString(m) }
func (*AntRet) ProtoMessage()               {}
func (*AntRet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AntRet) GetAck() bool {
	if m != nil {
		return m.Ack
	}
	return false
}

func (m *AntRet) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PingRet struct {
	Host         string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	NbNode       int32  `protobuf:"varint,3,opt,name=nb_node,json=nbNode" json:"nb_node,omitempty"`
	ClientNumber int32  `protobuf:"varint,4,opt,name=client_number,json=clientNumber" json:"client_number,omitempty"`
}

func (m *PingRet) Reset()                    { *m = PingRet{} }
func (m *PingRet) String() string            { return proto.CompactTextString(m) }
func (*PingRet) ProtoMessage()               {}
func (*PingRet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PingRet) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *PingRet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PingRet) GetNbNode() int32 {
	if m != nil {
		return m.NbNode
	}
	return 0
}

func (m *PingRet) GetClientNumber() int32 {
	if m != nil {
		return m.ClientNumber
	}
	return 0
}

type AskConnectionRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Ip   string `protobuf:"bytes,3,opt,name=ip" json:"ip,omitempty"`
}

func (m *AskConnectionRequest) Reset()                    { *m = AskConnectionRequest{} }
func (m *AskConnectionRequest) String() string            { return proto.CompactTextString(m) }
func (*AskConnectionRequest) ProtoMessage()               {}
func (*AskConnectionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AskConnectionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AskConnectionRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *AskConnectionRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type SendFileRequest struct {
	ClientId   string   `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Name       string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Path       string   `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	NbBlock    int64    `protobuf:"varint,4,opt,name=nb_block,json=nbBlock" json:"nb_block,omitempty"`
	BlockSize  int64    `protobuf:"varint,5,opt,name=blockSize" json:"blockSize,omitempty"`
	TransferId string   `protobuf:"bytes,6,opt,name=transfer_id,json=transferId" json:"transfer_id,omitempty"`
	Key        string   `protobuf:"bytes,7,opt,name=key" json:"key,omitempty"`
	Metadata   []string `protobuf:"bytes,8,rep,name=metadata" json:"metadata,omitempty"`
}

func (m *SendFileRequest) Reset()                    { *m = SendFileRequest{} }
func (m *SendFileRequest) String() string            { return proto.CompactTextString(m) }
func (*SendFileRequest) ProtoMessage()               {}
func (*SendFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SendFileRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *SendFileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SendFileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SendFileRequest) GetNbBlock() int64 {
	if m != nil {
		return m.NbBlock
	}
	return 0
}

func (m *SendFileRequest) GetBlockSize() int64 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *SendFileRequest) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

func (m *SendFileRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SendFileRequest) GetMetadata() []string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SendFileRet struct {
	TransferId string `protobuf:"bytes,1,opt,name=transfer_id,json=transferId" json:"transfer_id,omitempty"`
	BlockSize  int64  `protobuf:"varint,2,opt,name=block_size,json=blockSize" json:"block_size,omitempty"`
}

func (m *SendFileRet) Reset()                    { *m = SendFileRet{} }
func (m *SendFileRet) String() string            { return proto.CompactTextString(m) }
func (*SendFileRet) ProtoMessage()               {}
func (*SendFileRet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SendFileRet) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

func (m *SendFileRet) GetBlockSize() int64 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

type EmptyRet struct {
}

func (m *EmptyRet) Reset()                    { *m = EmptyRet{} }
func (m *EmptyRet) String() string            { return proto.CompactTextString(m) }
func (*EmptyRet) ProtoMessage()               {}
func (*EmptyRet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type GetFileRequest struct {
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *GetFileRequest) Reset()                    { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()               {}
func (*GetFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetFileRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *GetFileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetFileRet struct {
	TransferId string `protobuf:"bytes,1,opt,name=transfer_id,json=transferId" json:"transfer_id,omitempty"`
	BlockSize  int64  `protobuf:"varint,2,opt,name=block_size,json=blockSize" json:"block_size,omitempty"`
}

func (m *GetFileRet) Reset()                    { *m = GetFileRet{} }
func (m *GetFileRet) String() string            { return proto.CompactTextString(m) }
func (*GetFileRet) ProtoMessage()               {}
func (*GetFileRet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetFileRet) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

func (m *GetFileRet) GetBlockSize() int64 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func init() {
	proto.RegisterType((*AntMes)(nil), "gnode.AntMes")
	proto.RegisterType((*AntRet)(nil), "gnode.AntRet")
	proto.RegisterType((*PingRet)(nil), "gnode.PingRet")
	proto.RegisterType((*AskConnectionRequest)(nil), "gnode.AskConnectionRequest")
	proto.RegisterType((*SendFileRequest)(nil), "gnode.SendFileRequest")
	proto.RegisterType((*SendFileRet)(nil), "gnode.SendFileRet")
	proto.RegisterType((*EmptyRet)(nil), "gnode.EmptyRet")
	proto.RegisterType((*GetFileRequest)(nil), "gnode.GetFileRequest")
	proto.RegisterType((*GetFileRet)(nil), "gnode.GetFileRet")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GNodeService service

type GNodeServiceClient interface {
	ExecuteFunction(ctx context.Context, in *AntMes, opts ...grpc.CallOption) (*AntRet, error)
	GetClientStream(ctx context.Context, opts ...grpc.CallOption) (GNodeService_GetClientStreamClient, error)
	AskConnection(ctx context.Context, in *AskConnectionRequest, opts ...grpc.CallOption) (*PingRet, error)
	Ping(ctx context.Context, in *AntMes, opts ...grpc.CallOption) (*PingRet, error)
	SendFile(ctx context.Context, in *SendFileRequest, opts ...grpc.CallOption) (*SendFileRet, error)
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileRet, error)
}

type gNodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewGNodeServiceClient(cc *grpc.ClientConn) GNodeServiceClient {
	return &gNodeServiceClient{cc}
}

func (c *gNodeServiceClient) ExecuteFunction(ctx context.Context, in *AntMes, opts ...grpc.CallOption) (*AntRet, error) {
	out := new(AntRet)
	err := grpc.Invoke(ctx, "/gnode.GNodeService/ExecuteFunction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNodeServiceClient) GetClientStream(ctx context.Context, opts ...grpc.CallOption) (GNodeService_GetClientStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GNodeService_serviceDesc.Streams[0], c.cc, "/gnode.GNodeService/GetClientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gNodeServiceGetClientStreamClient{stream}
	return x, nil
}

type GNodeService_GetClientStreamClient interface {
	Send(*AntMes) error
	Recv() (*AntMes, error)
	grpc.ClientStream
}

type gNodeServiceGetClientStreamClient struct {
	grpc.ClientStream
}

func (x *gNodeServiceGetClientStreamClient) Send(m *AntMes) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gNodeServiceGetClientStreamClient) Recv() (*AntMes, error) {
	m := new(AntMes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gNodeServiceClient) AskConnection(ctx context.Context, in *AskConnectionRequest, opts ...grpc.CallOption) (*PingRet, error) {
	out := new(PingRet)
	err := grpc.Invoke(ctx, "/gnode.GNodeService/AskConnection", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNodeServiceClient) Ping(ctx context.Context, in *AntMes, opts ...grpc.CallOption) (*PingRet, error) {
	out := new(PingRet)
	err := grpc.Invoke(ctx, "/gnode.GNodeService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNodeServiceClient) SendFile(ctx context.Context, in *SendFileRequest, opts ...grpc.CallOption) (*SendFileRet, error) {
	out := new(SendFileRet)
	err := grpc.Invoke(ctx, "/gnode.GNodeService/SendFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNodeServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileRet, error) {
	out := new(GetFileRet)
	err := grpc.Invoke(ctx, "/gnode.GNodeService/GetFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GNodeService service

type GNodeServiceServer interface {
	ExecuteFunction(context.Context, *AntMes) (*AntRet, error)
	GetClientStream(GNodeService_GetClientStreamServer) error
	AskConnection(context.Context, *AskConnectionRequest) (*PingRet, error)
	Ping(context.Context, *AntMes) (*PingRet, error)
	SendFile(context.Context, *SendFileRequest) (*SendFileRet, error)
	GetFile(context.Context, *GetFileRequest) (*GetFileRet, error)
}

func RegisterGNodeServiceServer(s *grpc.Server, srv GNodeServiceServer) {
	s.RegisterService(&_GNodeService_serviceDesc, srv)
}

func _GNodeService_ExecuteFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AntMes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNodeServiceServer).ExecuteFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnode.GNodeService/ExecuteFunction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNodeServiceServer).ExecuteFunction(ctx, req.(*AntMes))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNodeService_GetClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GNodeServiceServer).GetClientStream(&gNodeServiceGetClientStreamServer{stream})
}

type GNodeService_GetClientStreamServer interface {
	Send(*AntMes) error
	Recv() (*AntMes, error)
	grpc.ServerStream
}

type gNodeServiceGetClientStreamServer struct {
	grpc.ServerStream
}

func (x *gNodeServiceGetClientStreamServer) Send(m *AntMes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gNodeServiceGetClientStreamServer) Recv() (*AntMes, error) {
	m := new(AntMes)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GNodeService_AskConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNodeServiceServer).AskConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnode.GNodeService/AskConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNodeServiceServer).AskConnection(ctx, req.(*AskConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNodeService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AntMes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNodeServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnode.GNodeService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNodeServiceServer).Ping(ctx, req.(*AntMes))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNodeService_SendFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNodeServiceServer).SendFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnode.GNodeService/SendFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNodeServiceServer).SendFile(ctx, req.(*SendFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNodeService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNodeServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnode.GNodeService/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNodeServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GNodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gnode.GNodeService",
	HandlerType: (*GNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteFunction",
			Handler:    _GNodeService_ExecuteFunction_Handler,
		},
		{
			MethodName: "AskConnection",
			Handler:    _GNodeService_AskConnection_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _GNodeService_Ping_Handler,
		},
		{
			MethodName: "SendFile",
			Handler:    _GNodeService_SendFile_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _GNodeService_GetFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetClientStream",
			Handler:       _GNodeService_GetClientStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server/gnode/gnode.proto",
}

func init() { proto.RegisterFile("server/gnode/gnode.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 764 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x55, 0xdb, 0x6e, 0xe3, 0x36,
	0x10, 0x8d, 0xe4, 0x9b, 0x34, 0xf1, 0x25, 0x61, 0x93, 0x94, 0x75, 0x1a, 0xd4, 0x50, 0x0b, 0xd4,
	0xe8, 0x43, 0x52, 0xb4, 0x08, 0xd0, 0xa7, 0x02, 0x4e, 0x90, 0x04, 0x01, 0x9a, 0x20, 0x90, 0x1f,
	0xfa, 0x28, 0x48, 0xd6, 0xc4, 0x21, 0x6c, 0x53, 0x5e, 0x8a, 0xce, 0x65, 0x3f, 0x6f, 0xbf, 0x60,
	0xbf, 0x60, 0xbf, 0x65, 0xc1, 0xa1, 0xe4, 0x38, 0xf6, 0x62, 0x5f, 0xf2, 0x62, 0xcc, 0x39, 0x9c,
	0x19, 0x1e, 0x0e, 0x0f, 0x65, 0xe0, 0x39, 0xaa, 0x47, 0x54, 0x27, 0x63, 0x99, 0xa5, 0x68, 0x7f,
	0x8f, 0xe7, 0x2a, 0xd3, 0x19, 0xab, 0x11, 0x08, 0x3e, 0x55, 0xa1, 0x3e, 0x90, 0xfa, 0x06, 0x73,
	0xd6, 0x06, 0x57, 0xa4, 0xdc, 0xe9, 0x39, 0x7d, 0x3f, 0x74, 0x45, 0xca, 0x0e, 0xa0, 0x9e, 0x29,
	0x31, 0x16, 0x92, 0xbb, 0xc4, 0x15, 0x88, 0xfd, 0x02, 0xdb, 0xf7, 0x2a, 0x9b, 0x45, 0xa3, 0xa9,
	0x40, 0xa9, 0x79, 0x85, 0x16, 0xc1, 0x50, 0xe7, 0xc4, 0x98, 0x42, 0x1d, 0xab, 0x31, 0x6a, 0x5e,
	0xb5, 0x85, 0x16, 0xb1, 0x2e, 0x78, 0x22, 0x1f, 0xc8, 0xfc, 0x09, 0x15, 0xaf, 0xf5, 0x9c, 0xbe,
	0x17, 0x2e, 0x31, 0xfb, 0x15, 0x5a, 0x0a, 0xf5, 0x42, 0xc9, 0x28, 0xb6, 0x09, 0x75, 0x4a, 0x68,
	0x5a, 0xb2, 0x48, 0xfa, 0x0d, 0xda, 0x22, 0x8f, 0xe6, 0xb1, 0x7e, 0x88, 0x9e, 0x94, 0xd0, 0xa8,
	0x78, 0xc3, 0x66, 0x89, 0xfc, 0x2e, 0xd6, 0x0f, 0xff, 0x13, 0xc7, 0x0e, 0xc1, 0xb7, 0x4a, 0x23,
	0x91, 0x72, 0x8f, 0x14, 0x78, 0x96, 0xb8, 0x4e, 0x19, 0x83, 0xaa, 0xa9, 0xe7, 0x7e, 0xaf, 0xd2,
	0xf7, 0x43, 0x8a, 0xd9, 0x11, 0x00, 0xf5, 0x14, 0x32, 0xc5, 0x67, 0x0e, 0x3d, 0xa7, 0x5f, 0x0b,
	0x7d, 0xc3, 0x5c, 0x1b, 0xc2, 0xc8, 0xbe, 0x5f, 0xc8, 0x91, 0x16, 0x99, 0xe4, 0xdb, 0xb6, 0x5d,
	0x89, 0x4d, 0xbb, 0x58, 0x8d, 0x73, 0xde, 0xb4, 0xed, 0x4c, 0x6c, 0xe6, 0xa3, 0x55, 0x2c, 0xf3,
	0x7b, 0x54, 0x46, 0x41, 0xcb, 0xce, 0xa7, 0xa4, 0xae, 0x53, 0xb6, 0x07, 0xb5, 0x4c, 0xa5, 0xa8,
	0x78, 0xbb, 0xe7, 0xf4, 0x2b, 0xa1, 0x05, 0xec, 0x27, 0xf0, 0x64, 0x12, 0x25, 0xd3, 0x6c, 0x34,
	0xe1, 0x1d, 0x5a, 0x68, 0xc8, 0xe4, 0xcc, 0x40, 0xa3, 0x40, 0xe1, 0x7c, 0x2a, 0x46, 0x71, 0xce,
	0x77, 0x48, 0xde, 0x12, 0x1b, 0x05, 0xb9, 0xf8, 0x88, 0x7c, 0x97, 0x4a, 0x28, 0x36, 0xc3, 0xb4,
	0x23, 0xc7, 0x94, 0xa6, 0xc5, 0x19, 0x69, 0x68, 0x96, 0xa4, 0x19, 0x96, 0x91, 0x29, 0x33, 0xbb,
	0x9f, 0x90, 0x63, 0xfe, 0x03, 0x4d, 0x12, 0x64, 0x76, 0x56, 0x30, 0x46, 0x66, 0x8a, 0xc9, 0x62,
	0xcc, 0xf7, 0x68, 0xc9, 0x02, 0xb3, 0x5f, 0x1a, 0xeb, 0x98, 0xef, 0xf7, 0x9c, 0x7e, 0x33, 0xa4,
	0x38, 0xf8, 0x83, 0x3c, 0x14, 0xa2, 0x66, 0x3b, 0x50, 0x89, 0x47, 0x13, 0x32, 0x91, 0x17, 0x9a,
	0xb0, 0x70, 0x95, 0x5b, 0xba, 0x2a, 0xc8, 0xa0, 0x71, 0x27, 0xe4, 0xd8, 0x24, 0x33, 0xa8, 0x3e,
	0x64, 0xb9, 0x2e, 0x2c, 0x47, 0xb1, 0xe1, 0x64, 0x3c, 0xc3, 0xa2, 0x80, 0x62, 0xf6, 0x23, 0x34,
	0x64, 0x12, 0x19, 0xbb, 0x92, 0xd9, 0x6a, 0x61, 0x5d, 0x26, 0xb7, 0x59, 0x4a, 0xe7, 0xb4, 0x26,
	0x8c, 0xe4, 0x62, 0x96, 0xa0, 0x22, 0xbf, 0xd5, 0xc2, 0xa6, 0x25, 0x6f, 0x89, 0x0b, 0x6e, 0x61,
	0x6f, 0x90, 0x4f, 0xce, 0x33, 0x29, 0x91, 0xee, 0x2c, 0xc4, 0x0f, 0x0b, 0x5c, 0xd9, 0xc9, 0x59,
	0xd9, 0xa9, 0x54, 0xe4, 0xae, 0x28, 0x32, 0x07, 0x98, 0x17, 0x2e, 0x77, 0xc5, 0x3c, 0xf8, 0xe2,
	0x40, 0x67, 0x88, 0x32, 0xbd, 0x14, 0x53, 0x2c, 0x7b, 0x1d, 0x82, 0x5f, 0x08, 0x59, 0xbe, 0x20,
	0xcf, 0x12, 0xd6, 0x72, 0x1b, 0x47, 0x2a, 0x6d, 0x68, 0xdb, 0x5a, 0x1b, 0xae, 0x1a, 0xa0, 0xfa,
	0xd6, 0x00, 0x3f, 0x83, 0x4f, 0xfc, 0xd0, 0xdc, 0x74, 0x8d, 0xd6, 0x5e, 0x89, 0x75, 0xc3, 0xd5,
	0x37, 0x0c, 0xb7, 0x03, 0x95, 0x09, 0xbe, 0xd0, 0x63, 0xf1, 0x43, 0x13, 0x1a, 0x47, 0xcd, 0x50,
	0xc7, 0x74, 0x93, 0x1e, 0x79, 0x77, 0x89, 0x83, 0x1b, 0xd8, 0x7e, 0x3d, 0x9f, 0x5e, 0xef, 0xee,
	0x6c, 0x74, 0x3f, 0x02, 0x20, 0x2d, 0x11, 0xf9, 0xd0, 0x5d, 0x53, 0x17, 0x00, 0x78, 0x17, 0xb3,
	0xb9, 0x7e, 0x09, 0x51, 0x07, 0x03, 0x68, 0x5f, 0xa1, 0x7e, 0xcf, 0xe4, 0x82, 0xff, 0x00, 0x96,
	0x2d, 0xde, 0x2d, 0xee, 0xaf, 0xcf, 0x2e, 0x34, 0xaf, 0x8c, 0x97, 0x86, 0xa8, 0x1e, 0xc5, 0x08,
	0xd9, 0x09, 0x74, 0x2e, 0x9e, 0x71, 0xb4, 0xd0, 0x78, 0x59, 0xbe, 0xf1, 0xd6, 0xb1, 0xfd, 0x6e,
	0xda, 0xcf, 0x64, 0x77, 0x05, 0x1a, 0x05, 0xa7, 0xd0, 0xb9, 0x42, 0x6d, 0xbf, 0x7c, 0x43, 0xad,
	0x30, 0x9e, 0x7d, 0xa7, 0xe0, 0x06, 0xf3, 0x60, 0xab, 0xef, 0xfc, 0xe9, 0xb0, 0x7f, 0xa1, 0xf5,
	0xc6, 0x95, 0xec, 0xb0, 0xcc, 0xfa, 0x86, 0x57, 0xbb, 0xed, 0x62, 0xb1, 0x78, 0x39, 0xc1, 0x16,
	0xfb, 0x1d, 0xaa, 0x06, 0xac, 0xef, 0xb5, 0x99, 0xf8, 0x0f, 0x78, 0xe5, 0x6d, 0xb2, 0x83, 0x62,
	0x75, 0xcd, 0xbe, 0x5d, 0xb6, 0xc1, 0x9b, 0xca, 0x53, 0x68, 0x14, 0x93, 0x66, 0xfb, 0x45, 0xc2,
	0xdb, 0xcb, 0xeb, 0xee, 0xae, 0xd3, 0x3a, 0xd8, 0x4a, 0xea, 0xf4, 0xff, 0xf2, 0xf7, 0xd7, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x67, 0x40, 0x54, 0xae, 0x7b, 0x06, 0x00, 0x00,
}
